spring.application.name=Breathe-esg

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://ephyr.proxy.rlwy.net:10039/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=UDEMMXPHckUXWYqIJCUEzYNaQTAcebIC

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true